teams:
  red:
    spawn-location:
      world:
      x:
      y:
      z:
      yaw:
      pitch:
    wither-location:
      world:
      x:
      y:
      z:
    protection-region:
      point-1:
        world:
        x:
        y:
        z:
      point-2:
        world:
        x:
        y:
        z:
    wither-region:
      point-1:
        world:
        x:
        y:
        z:
      point-2:
        world:
        x:
        y:
        z:
