name: KireiWalls
version: '${project.version}'
main: dev.tqqn.kireiwalls.KireiWalls
api-version: '1.20'
commands:
  debug:
    description: Debug command
    usage: /<command>
  witherdebug:
    description: Wither Debug command
    usage: /<command>
  build:
    description: Build command
    usage: /<command>
  spectate:
    description: Spectate command
    usage: /<command>